### ISSUE TITLE
[Idea] Instructions

### ISSUE THREAD

**Issue by ankane** [gregrahn/tpch-kit#2]
Hey @gregrahn, the modifications you've made to TPC-H seem really useful. Do you mind documenting how to use the project? The instructions for `tpcds-kit` are great.

**Comment by gregrahn** [comment]
Fixed via 852ad0a5ee31ebefeed884cea4188781dd9613a3

**Comment by ankane** [comment]
Awesome, thanks @gregrahn 👍
